### ISSUE TITLE
ERROR - ERROR

### ISSUE THREAD

**Issue by liakjim** [vincent-lwt/RaspberryCast#94]
Hi, raspberry will not play youtube videos anymore. 
The screen says that video is processing, then ready but nothing happens.
RaspberryCast.log returns :
ERROR - ERROR: 4XDHmnzT46M: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I have latest version of youtube-dl installed. 
youtube-dl -U returns:
youtube-dl is up-to-date (2019.04.24)

**Comment by tedchou12** [comment]
Seems like I am facing the same situation...

**Comment by mheine** [comment]
Weird. Seems to be an issue with youtube-dl, and having a look at their issues there have been a few similar cases like this in the past, but they've all been attributed to old versions of youtube-dl.
Are you able to download the video "manually" (as in, using the standalone version of `youtube-dl`, and not using RaspberryCast)?

**Comment by liakjim** [comment]
> Weird. Seems to be an issue with youtube-dl, and having a look at their issues there have been a few similar cases like this in the past, but they've all been attributed to old versions of youtube-dl.
> Are you able to download the video "manually" (as in, using the standalone version of `youtube-dl`, and not using RaspberryCast)?

It seems that it does : 
![image](https://user-images.githubusercontent.com/50009597/57096216-68214200-6d1d-11e9-82c9-a9d6656f50fc.png)

**Comment by elblogbruno** [comment]
I fixed it by updating youtube-dl to the latest version and rebooting my raspberry pi!

**Comment by liakjim** [comment]
> I fixed it by updating youtube-dl to the latest version and rebooting my raspberry pi!

Did you update with youtube-dl -U command? Or something else? If yes, which version it installed? In my case it returns this  : "youtube-dl is up-to-date (2019.04.24)".
The problem remains though.

**Comment by elblogbruno** [comment]
I run `sudo -H pip install --upgrade youtube-dl`  to update using Pip.
Here's my youtube-dl version.
![image](https://user-images.githubusercontent.com/10481058/57176877-f1d82900-6e5d-11e9-942f-4bafa47f75ca.png)
then run `sudo reboot` to reboot.

**Comment by liakjim** [comment]
> I fixed it by updating youtube-dl to the latest version and rebooting my raspberry pi!

Did you update with youtube-dl -U command? Or something else? If yes, which version it installed? In my case it returns this  : "youtube-dl is up-to-date (2019.04.24)".
The problem remains though.

> I run `sudo -H pip install --upgrade youtube-dl` to update using Pip.
> Here's my youtube-dl version.
> ![image](https://user-images.githubusercontent.com/10481058/57176877-f1d82900-6e5d-11e9-942f-4bafa47f75ca.png)
> then run `sudo reboot` to reboot.

Oh, there is a new version out as it seems. I will try when back at home and report. Thanks

**Comment by liakjim** [comment]
Ok, 2019.04.30 version seems to be working !!!!
Thanks @elblogbruno

**Comment by elblogbruno** [comment]
@liakjim  You're welcome!

**Comment by liakjim** [comment]
Now it seems to be another issue. 
When raspberry login, there is the "raspberrycast is ready" screen . 
https://i.postimg.cc/6QSk8V1C/ready.jpg 

It won't go away. 

@elblogbruno , is it the same with you?

**Comment by elblogbruno** [comment]
I believe its not an error as RaspberryCast intention is to work that way, as a chromecast device when you plug it in a tv.
I disabled this screen because I didn't want to have it for my project, I'll show you how later if you need to.

**Comment by liakjim** [comment]
> I believe its not an error as RaspberryCast intention is to work that way, as a chromecast device when you plug it in a tv.
> I disabled this screen because I didn't want to have it for my project, I'll show you how later if you need to.

Yes please.

**Comment by elblogbruno** [comment]
Check my fork: https://github.com/elblogbruno/RaspberryCast
you'll see the commits i've made to the files

**Comment by DanielGlaas** [comment]
Hi guys,
If you don't want that these screens are displayed, then just set the value of 'new_log' to 'false' in the raspberrycast.conf file.
This variable only serves for this purpose and for nothing else.

**Comment by DanielGlaas** [comment]
As the requested behaviour can be archived by the configuration file, I recommend to close this issue.

**Comment by elblogbruno** [comment]
Didn't know that thanks!

**Comment by liakjim** [comment]
> 
> 
> Hi guys,
> If you don't want that these screens are displayed, then just set the value of 'new_log' to 'false' in the raspberrycast.conf file.
> This variable only serves for this purpose and for nothing else.

This fixed this issue. Many thanks!
